<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGHI48Gz\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGHI48Gz/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGHI48Gz.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGHI48Gz\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGHI48Gz\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GHI48Gz',
    'container.build_id' => 'efd2de94',
    'container.build_time' => 1633285133,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGHI48Gz');
