<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container36zyda5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container36zyda5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container36zyda5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container36zyda5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container36zyda5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '36zyda5',
    'container.build_id' => 'bdf19ae9',
    'container.build_time' => 1633879466,
], __DIR__.\DIRECTORY_SEPARATOR.'Container36zyda5');
