<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLorLxZY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLorLxZY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLorLxZY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLorLxZY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLorLxZY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LorLxZY',
    'container.build_id' => '1c4274d1',
    'container.build_time' => 1633286724,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLorLxZY');
